<a href="https://colab.research.google.com/github/manideep099/big-data-assignments/blob/main/ICP2__700770025(neural).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
def fullname(first_name, last_name):
    return first_name + " " + last_name


def string_alternative(full_name):
    return full_name[::2]


def main():
    first_name = input("Enter first name: ")
    last_name = input("Enter last name: ")

    full_name = fullname(first_name, last_name)
    print("Full Name:", full_name)

    alt_string = string_alternative(full_name)
    print("Alternate characters:", alt_string)


if __name__ == "__main__":
    main()


Enter first name: hello
Enter last name: world
Full Name: hello world
Alternate characters: hlowrd


In [ ]:

with open("input.txt", "r") as file:
    lines = file.readlines()

word_count = {}

for line in lines:
    words = line.strip().split()
    for word in words:
        word_count[word] = word_count.get(word, 0) + 1

with open("output.txt", "w") as out:
    for line in lines:
        out.write(line)
    out.write("Word_Count:\n")
    for word, count in word_count.items():
        out.write(f"{word}: {count}\n")

for line in lines:
    print(line.strip())
print("Word_Count:")
for word, count in word_count.items():
    print(f"{word}: {count}")


Python Course
Deep Learning Course
Word_Count:
Python: 1
Course: 2
Deep: 1
Learning: 1


In [ ]:
L1 = [150, 155, 145, 148]
L2 = []

for h in L1:
    inches = h / 2.54
    L2.append(round(inches, 2))

print("Converted heights:", L2)


Converted heights: [59.06, 61.02, 57.09, 58.27]


In [ ]:
L1 = [150, 155, 145, 148]

L2 = [round(h / 2.54, 2) for h in L1]

print("Converted heights:", L2)


Converted heights: [59.06, 61.02, 57.09, 58.27]


In [2]:
class Employee:
    employee_count = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1

    def average_salary(self):
        return self.salary


class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)

emp1 = Employee("Rajesh", "M", 50000, "HR")
emp2 = FulltimeEmployee("Manideep", "Pothuraju", 100000, "IT")

print("Employee 1 Salary:", emp1.average_salary())
print("Employee 2 Salary:", emp2.average_salary())
print("Total Employees:", Employee.employee_count)


Employee 1 Salary: 50000
Employee 2 Salary: 100000
Total Employees: 2


In [ ]:
import numpy as np

arr = np.random.uniform(1, 20, 20)

arr = arr.reshape(4, 5)

print("Original Array:\n", arr)

row_max = arr.max(axis=1, keepdims=True)
arr[arr == row_max] = 0

print("\nModified Array:\n", arr)


Original Array:
 [[13.16994902  1.84066701 16.75408819 17.00248675 13.28050733]
 [10.27852696  4.40310345  9.42238469  7.6581861  19.75766589]
 [ 7.99321523 15.78789309 14.96978928 13.47058046  4.42162557]
 [ 7.44960812  6.76490953 18.65338787  9.83233192 16.6762857 ]]

Modified Array:
 [[13.16994902  1.84066701 16.75408819  0.         13.28050733]
 [10.27852696  4.40310345  9.42238469  7.6581861   0.        ]
 [ 7.99321523  0.         14.96978928 13.47058046  4.42162557]
 [ 7.44960812  6.76490953  0.          9.83233192 16.6762857 ]]
